INSERT INTO `final_team2`.`programming_category` (`progCt_name`) VALUES ('웹 개발');
INSERT INTO `final_team2`.`programming_category` (`progCt_name`) VALUES ('프론트엔드');
INSERT INTO `final_team2`.`programming_category` (`progCt_name`) VALUES ('백엔드');
INSERT INTO `final_team2`.`programming_category` (`progCt_name`) VALUES ('풀스택');
INSERT INTO `final_team2`.`programming_category` (`progCt_name`) VALUES ('프로그래밍 언어');
INSERT INTO `final_team2`.`programming_category` (`progCt_name`) VALUES ('데이터베이스');
INSERT INTO `final_team2`.`programming_category` (`progCt_name`) VALUES ('웹 퍼블리싱');

INSERT INTO `final_team2`.`programming_language` (`lang_name`) VALUES ('JavaScript');
INSERT INTO `final_team2`.`programming_language` (`lang_name`) VALUES ('HTML/CSS');
INSERT INTO `final_team2`.`programming_language` (`lang_name`) VALUES ('React');
INSERT INTO `final_team2`.`programming_language` (`lang_name`) VALUES ('Java');
INSERT INTO `final_team2`.`programming_language` (`lang_name`) VALUES ('Spring');
INSERT INTO `final_team2`.`programming_language` (`lang_name`) VALUES ('Spring Boot');
INSERT INTO `final_team2`.`programming_language` (`lang_name`) VALUES ('Node.js');
INSERT INTO `final_team2`.`programming_language` (`lang_name`) VALUES ('Python');
INSERT INTO `final_team2`.`programming_language` (`lang_name`) VALUES ('Vue.js');
INSERT INTO `final_team2`.`programming_language` (`lang_name`) VALUES ('jQuery');
INSERT INTO `final_team2`.`programming_language` (`lang_name`) VALUES ('Firebase');
INSERT INTO `final_team2`.`programming_language` (`lang_name`) VALUES ('C');
INSERT INTO `final_team2`.`programming_language` (`lang_name`) VALUES ('C++');
INSERT INTO `final_team2`.`programming_language` (`lang_name`) VALUES ('C#');
INSERT INTO `final_team2`.`programming_language` (`lang_name`) VALUES ('Swift');
INSERT INTO `final_team2`.`programming_language` (`lang_name`) VALUES ('알고리즘');
INSERT INTO `final_team2`.`programming_language` (`lang_name`) VALUES ('SQL');
INSERT INTO `final_team2`.`programming_language` (`lang_name`) VALUES ('DBMS/RDBMS');
INSERT INTO `final_team2`.`programming_language` (`lang_name`) VALUES ('MySQL');
INSERT INTO `final_team2`.`programming_language` (`lang_name`) VALUES ('데이터 엔지니어링');
INSERT INTO `final_team2`.`programming_language` (`lang_name`) VALUES ('Oracle');
INSERT INTO `final_team2`.`programming_language` (`lang_name`) VALUES ('빅데이터');
INSERT INTO `final_team2`.`programming_language` (`lang_name`) VALUES ('backend');
INSERT INTO `final_team2`.`programming_language` (`lang_name`) VALUES ('인터랙티브 웹');
INSERT INTO `final_team2`.`programming_language` (`lang_name`) VALUES ('반응형 웹');
INSERT INTO `final_team2`.`programming_language` (`lang_name`) VALUES ('웹 디자인');
INSERT INTO `final_team2`.`programming_language` (`lang_name`) VALUES ('클론코딩');
INSERT INTO `final_team2`.`programming_language` (`lang_name`) VALUES ('포트폴리오');
INSERT INTO `final_team2`.`programming_language` (`lang_name`) VALUES ('Sass');

INSERT INTO `final_team2`.`search_menu` (`sear_progCt_num`, `sear_lang_num`) VALUES ('1', '1');
INSERT INTO `final_team2`.`search_menu` (`sear_progCt_num`, `sear_lang_num`) VALUES ('1', '2');
INSERT INTO `final_team2`.`search_menu` (`sear_progCt_num`, `sear_lang_num`) VALUES ('1', '3');
INSERT INTO `final_team2`.`search_menu` (`sear_progCt_num`, `sear_lang_num`) VALUES ('1', '4');
INSERT INTO `final_team2`.`search_menu` (`sear_progCt_num`, `sear_lang_num`) VALUES ('1', '5');
INSERT INTO `final_team2`.`search_menu` (`sear_progCt_num`, `sear_lang_num`) VALUES ('1', '6');
INSERT INTO `final_team2`.`search_menu` (`sear_progCt_num`, `sear_lang_num`) VALUES ('1', '7');
INSERT INTO `final_team2`.`search_menu` (`sear_progCt_num`, `sear_lang_num`) VALUES ('1', '8');
INSERT INTO `final_team2`.`search_menu` (`sear_progCt_num`, `sear_lang_num`) VALUES ('1', '9');
INSERT INTO `final_team2`.`search_menu` (`sear_progCt_num`, `sear_lang_num`) VALUES ('1', '10');
INSERT INTO `final_team2`.`search_menu` (`sear_progCt_num`, `sear_lang_num`) VALUES ('2', '1');
INSERT INTO `final_team2`.`search_menu` (`sear_progCt_num`, `sear_lang_num`) VALUES ('2', '3');
INSERT INTO `final_team2`.`search_menu` (`sear_progCt_num`, `sear_lang_num`) VALUES ('2', '2');
INSERT INTO `final_team2`.`search_menu` (`sear_progCt_num`, `sear_lang_num`) VALUES ('2', '9');
INSERT INTO `final_team2`.`search_menu` (`sear_progCt_num`, `sear_lang_num`) VALUES ('2', '7');
INSERT INTO `final_team2`.`search_menu` (`sear_progCt_num`, `sear_lang_num`) VALUES ('2', '10');
INSERT INTO `final_team2`.`search_menu` (`sear_progCt_num`, `sear_lang_num`) VALUES ('2', '24');
INSERT INTO `final_team2`.`search_menu` (`sear_progCt_num`, `sear_lang_num`) VALUES ('2', '4');
INSERT INTO `final_team2`.`search_menu` (`sear_progCt_num`, `sear_lang_num`) VALUES ('2', '5');
INSERT INTO `final_team2`.`search_menu` (`sear_progCt_num`, `sear_lang_num`) VALUES ('3', '4');
INSERT INTO `final_team2`.`search_menu` (`sear_progCt_num`, `sear_lang_num`) VALUES ('3', '5');
INSERT INTO `final_team2`.`search_menu` (`sear_progCt_num`, `sear_lang_num`) VALUES ('3', '6');
INSERT INTO `final_team2`.`search_menu` (`sear_progCt_num`, `sear_lang_num`) VALUES ('3', '7');
INSERT INTO `final_team2`.`search_menu` (`sear_progCt_num`, `sear_lang_num`) VALUES ('3', '1');
INSERT INTO `final_team2`.`search_menu` (`sear_progCt_num`, `sear_lang_num`) VALUES ('3', '8');
INSERT INTO `final_team2`.`search_menu` (`sear_progCt_num`, `sear_lang_num`) VALUES ('3', '3');
INSERT INTO `final_team2`.`search_menu` (`sear_progCt_num`, `sear_lang_num`) VALUES ('4', '1');
INSERT INTO `final_team2`.`search_menu` (`sear_progCt_num`, `sear_lang_num`) VALUES ('4', '3');
INSERT INTO `final_team2`.`search_menu` (`sear_progCt_num`, `sear_lang_num`) VALUES ('4', '7');
INSERT INTO `final_team2`.`search_menu` (`sear_progCt_num`, `sear_lang_num`) VALUES ('4', '8');
INSERT INTO `final_team2`.`search_menu` (`sear_progCt_num`, `sear_lang_num`) VALUES ('4', '2');
INSERT INTO `final_team2`.`search_menu` (`sear_progCt_num`, `sear_lang_num`) VALUES ('4', '4');
INSERT INTO `final_team2`.`search_menu` (`sear_progCt_num`, `sear_lang_num`) VALUES ('4', '5');
INSERT INTO `final_team2`.`search_menu` (`sear_progCt_num`, `sear_lang_num`) VALUES ('4', '6');
INSERT INTO `final_team2`.`search_menu` (`sear_progCt_num`, `sear_lang_num`) VALUES ('4', '11');
INSERT INTO `final_team2`.`search_menu` (`sear_progCt_num`, `sear_lang_num`) VALUES ('5', '8');
INSERT INTO `final_team2`.`search_menu` (`sear_progCt_num`, `sear_lang_num`) VALUES ('5', '1');
INSERT INTO `final_team2`.`search_menu` (`sear_progCt_num`, `sear_lang_num`) VALUES ('5', '4');
INSERT INTO `final_team2`.`search_menu` (`sear_progCt_num`, `sear_lang_num`) VALUES ('5', '12');
INSERT INTO `final_team2`.`search_menu` (`sear_progCt_num`, `sear_lang_num`) VALUES ('5', '13');
INSERT INTO `final_team2`.`search_menu` (`sear_progCt_num`, `sear_lang_num`) VALUES ('5', '14');
INSERT INTO `final_team2`.`search_menu` (`sear_progCt_num`, `sear_lang_num`) VALUES ('5', '15');
INSERT INTO `final_team2`.`search_menu` (`sear_progCt_num`, `sear_lang_num`) VALUES ('5', '16');
INSERT INTO `final_team2`.`search_menu` (`sear_progCt_num`, `sear_lang_num`) VALUES ('6', '17');
INSERT INTO `final_team2`.`search_menu` (`sear_progCt_num`, `sear_lang_num`) VALUES ('6', '18');
INSERT INTO `final_team2`.`search_menu` (`sear_progCt_num`, `sear_lang_num`) VALUES ('6', '19');
INSERT INTO `final_team2`.`search_menu` (`sear_progCt_num`, `sear_lang_num`) VALUES ('6', '20');
INSERT INTO `final_team2`.`search_menu` (`sear_progCt_num`, `sear_lang_num`) VALUES ('6', '21');
INSERT INTO `final_team2`.`search_menu` (`sear_progCt_num`, `sear_lang_num`) VALUES ('6', '8');
INSERT INTO `final_team2`.`search_menu` (`sear_progCt_num`, `sear_lang_num`) VALUES ('6', '4');
INSERT INTO `final_team2`.`search_menu` (`sear_progCt_num`, `sear_lang_num`) VALUES ('6', '22');
INSERT INTO `final_team2`.`search_menu` (`sear_progCt_num`, `sear_lang_num`) VALUES ('6', '23');
INSERT INTO `final_team2`.`search_menu` (`sear_progCt_num`, `sear_lang_num`) VALUES ('7', '2');
INSERT INTO `final_team2`.`search_menu` (`sear_progCt_num`, `sear_lang_num`) VALUES ('7', '10');
INSERT INTO `final_team2`.`search_menu` (`sear_progCt_num`, `sear_lang_num`) VALUES ('7', '24');
INSERT INTO `final_team2`.`search_menu` (`sear_progCt_num`, `sear_lang_num`) VALUES ('7', '1');
INSERT INTO `final_team2`.`search_menu` (`sear_progCt_num`, `sear_lang_num`) VALUES ('7', '25');
INSERT INTO `final_team2`.`search_menu` (`sear_progCt_num`, `sear_lang_num`) VALUES ('7', '26');
INSERT INTO `final_team2`.`search_menu` (`sear_progCt_num`, `sear_lang_num`) VALUES ('7', '27');
INSERT INTO `final_team2`.`search_menu` (`sear_progCt_num`, `sear_lang_num`) VALUES ('7', '28');
INSERT INTO `final_team2`.`search_menu` (`sear_progCt_num`, `sear_lang_num`) VALUES ('7', '29');
