CREATE EVENT DELETE_CERTIFICATION
ON SCHEDULE EVERY 1 second
DO
	DELETE FROM CERTIFICATION WHERE CE_LIMIT <= NOW();
    
select * from shoppingmall.certification;

# 이벤트 조회
SELECT * FROM INFORMATION_SCHEMA.EVENTS;

# 이벤트 삭제
DROP EVENT DELETE_CERTIFICATION;

# 지정 시간에 이벤트가 1번만 실행되고 이벤트를 삭제 : NOT PRESERVE
CREATE EVENT DELETE_CERTIFICATION
ON SCHEDULE
AT '2024-02-15 09:45:00'
ON COMPLETION NOT PRESERVE
DO
	DELETE FROM CERTIFICATION WHERE CE_LIMIT <= NOW();